
#How to create an empty vector in R.
```{r}
vectorr<-c() #Not providing any arguments and hence we have created an empty array.
vectorr


#Nested empty vectors can also be created.
aa=c(c(),c())
aa

#We have gotten both the output as null.
```
#Using vectors
```{r}
vectorrr<-vector()
vectorrr

#We get the output as logical zero.

#How is c() and vector() different?
?c()

#Combine Values into a Vector or List
#Description
#This is a generic function which combines its arguments.

#The default method combines its arguments to form a vector. All arguments are coerced to a common type which is the type of the returned value, and all attributes except names are removed.


?vector()
#Vectors - Creation, Coercion, etc
#Description
#A vector in R is either an atomic vector i.e., one of the atomic types, see ‘Details’, or of type (typeof) or mode list or expression.

#vector produces a ‘simple’ vector of the given length and mode, where a ‘simple’ vector has no attribute, i.e., fulfills is.null(attributes(.)).

#as.vector, a generic, attempts to coerce its argument into a vector of mode mode (the default is to coerce to whichever vector mode is most convenient): if the result is atomic (is.atomic), all attributes are removed. For mode="any", see ‘Details’.


#So, a vector checks whether something is a vector or not.. c() will convert given values into a vector.


```
#Creating empty vectors using NULL.

```{r}

vector_name<-NULL
vector_name
#Value is null.

```

```{r}
vec<-numeric()
vec
#numeric is a general test to check whether a vector is numeric or not. It will return TRUE only if the object passed to it is a vector and consists of only numeric data. Whereas, is. vector tests whether the object is a vector or not.


#We get the output as numeric(0) meaning no output was given.
```

```{r}
vecc<-rep()
vecc

?rep()

#Replicate Elements of Vectors and Lists
#Description
#rep replicates the values in x. It is a generic function, and the (internal) default method is described here.

#rep.int and rep_len are faster simplified versions for two common cases. Internally, they are generic, so methods can be defined for them (see InternalMethods).
```
#______________________________________________________________________________________


#Create empty vectors and append values.
```{r}

new_vec<-c()

new_vec=1:10
new_vec

```

```{r}

#Just filling up that vector
ab<-c()
ab<-c("Shravan","Shiva",TRUE,7)
ab
typeof(ab)

```


```{r}
#Using index locations.
abc<-c()
abc[1]<-2
#Purposely skipped the value for index 2, so when I am printing it below I am getting NA as the value in second index.
abc[3]<-7
abc
typeof(abc) #Output is double.

```


```{r}
#Using append
abcc<-c()
abcc=append(abcc,2) #A bit different than what we do in python
abcc=append(abcc,c(3:10))
abcc

```
#Find Sum, Mean and Product of a Vector in R

```{r}

#mean() function is used to calculate mean
#Parameters:

#    x: Numeric Vector
 #   na.rm: Boolean value to ignore NA value

num_vec<-c(1:5)
mean(num_vec) #We get the value as 3.
sum(num_vec) #We get the value as 15

#IN THE ABOVE EXAMPLES WE HAVE ALSO CONSIDERED NA VALUES

#To find product of vectors
prod(num_vec) #We get the output as 120


#So we have the option to not consider NA values in our dataset
abc
mean(abc,na.rm=TRUE) 
```


```{r}
vec = c(1.1,NA, 2, 3.0,NA )
print("Sum of the vector:")

# inbuilt sum method
print(sum(vec))

# using inbuilt mean method
print("Mean of the vector with NaN values:")

# not ignoring NaN values
print(mean(vec))

# ignoring missing values
print("Mean of the vector without NaN values:")
print(mean(vec,na.rm = TRUE))

# using inbuilt product method
print("Product of the vector:")
print(prod(vec))

```


